"""add conversation_id and yaml_output to chat_history

Revision ID: c753235d91e8
Revises: a2a52192979d
Create Date: 2026-09-16 10:13:58.755487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c753235d91e8'
down_revision: Union[str, Sequence[str], None] = 'a2a52192979d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('conversation_id', sa.Integer(), nullable=True))
    op.add_column('chat_history', sa.Column('yaml_output', sa.Text(), nullable=True))
    op.create_index(op.f('ix_chat_history_conversation_id'), 'chat_history', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
    # 기존 행 백필: 레거시 1문답 행은 각자 단독 대화로 취급
    op.execute("UPDATE chat_history SET conversation_id = id WHERE conversation_id IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_history_conversation_id'), table_name='chat_history')
    op.drop_column('chat_history', 'yaml_output')
    op.drop_column('chat_history', 'conversation_id')
    # ### end Alembic commands ###
